### ISSUE TITLE
Bot started, but didn't claim reward and no error in log

### ISSUE THREAD

**Issue by darkGrimoire** [darkGrimoire/hoyolab-daily-bot#1]
Only BOT STARTED is in log.

**Comment by darkGrimoire** [comment]
Please login again to your hoyolab account in browser. This behaviour means the cookie is expired, though it's not intended to behave like this. This will be fixed on the next update

**Comment by kyraex** [comment]
I would like to inquire some information regarding this. Does this works for browser with multiple profile? (i.e Chrome) Because I tried to re-login using my chrome that has a number of profile but it still doesn't work. When I logged in using my Edge then it finally works.

**Comment by darkGrimoire** [comment]
yes, currently this program doesn't support multiple account.

**Comment by darkGrimoire** [comment]
Fixed in 1.1.0 release
