### ISSUE TITLE
Failed To Find Login Info

### ISSUE THREAD

**Issue by w3djyt** [darkGrimoire/hoyolab-daily-bot#14]
I was using Firefox from the start and it just suddenly stopped working. I tried uninstalling and reinstalling and double checking I'm logged in everywhere (Firefox and Edge)... Fiddled with the config file... nothing. No changes are making any difference. :/

**Comment by EffortlessFury** [comment]
I solved the issue by switching from Edge to Firefox and then also had to visit the check-in itself. Visiting the check-in page didn't solve the Edge issue, though. Very strange.

**Comment by w3djyt** [comment]
I went back and cleared out all cache/cookies/history/everything of firefox. Then I removed the bot and completely deleted all files from the system. Then rebooted, redownloaded the bot, logged in via firefox again, and set the bot to only use firefox, and changed the name of the bot. Told it to run again and after a few forced runs, it seems to have run for the last three days.

/shrug?
