### ISSUE TITLE
Adding a randomized delay

### ISSUE THREAD

**Issue by Alcas1** [darkGrimoire/hoyolab-daily-bot#4]
Could we possibly specify a randomized delay in the configuration file? I feel like it’s too consistent at the same time

**Comment by darkGrimoire** [comment]
That would be a great idea for safety reasons. I'll add it in the next release. Thanks for your suggestion!

**Comment by Alcas1** [comment]
any update on this? I feel like this is something that is better completed sooner than later

**Comment by darkGrimoire** [comment]
Sorry for leaving this. I just though I can combine the update with the other ones. I'll launch an update for this in the next few days.

**Comment by darkGrimoire** [comment]
Feature added at [v1.1.5](https://github.com/darkGrimoire/hoyolab-daily-bot/releases/tag/v1.1.5) update
