### ISSUE TITLE
Readme/setup clarification or handle python's virtual environment correctly in Windows Task scheduler

### ISSUE THREAD

**Issue by Matsumotorise** [darkGrimoire/hoyolab-daily-bot#7]
If the user only sets up his environment as instructed in the README, using the virtual environment, windows task scheduler doesn't have access to the required libs since it doesn't seem to run activate.ps1/activate. 

Either instruct the user to install the requirements.txt on the overall system, or handle this, possibly with a .bat wrapper file.

**Comment by darkGrimoire** [comment]
Can you please elaborate more about how're you doing this? Are you using the scheduler without the executable?

If you're using the scheduler, I do not intend to use this as it is without the executable in the release though. But, I'll try to check with the problem if I can.

**Comment by darkGrimoire** [comment]
I've added .bat wrapper file in [v1.1.5](https://github.com/darkGrimoire/hoyolab-daily-bot/releases/tag/v1.1.5) update. Thank you for your report!
